import type { NextPage } from 'next'
import Head from 'next/head'
import styled from "styled-components";
import NftDropPage from "./nft/NftDropPage";

const Home: NextPage = () => {
    return (
        <Container>
            <Head>
                <title>NFT drop</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NftDropPage />
        </Container>
    )
}

const Container = styled.div`
  width: 100%;
  height: 100vh;
  display: flex;
  flex-direction: row;
  align-items: flex-start;
  justify-content: flex-start;
`

export default Home
